// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jobmatcher.domain;

import com.jobmatcher.domain.JobDataOnDemand;
import com.jobmatcher.domain.JobIntegrationTest;
import com.jobmatcher.service.JobService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect JobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    JobDataOnDemand JobIntegrationTest.dod;
    
    @Autowired
    JobService JobIntegrationTest.jobService;
    
    @Test
    public void JobIntegrationTest.testCountAllJobs() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobService.countAllJobs();
        Assert.assertTrue("Counter for 'Job' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFindJob() {
        Job obj = dod.getRandomJob();
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Job' failed to provide an identifier", id);
        obj = jobService.findJob(id);
        Assert.assertNotNull("Find method for 'Job' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Job' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testFindAllJobs() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobService.countAllJobs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Job', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Job> result = jobService.findAllJobs();
        Assert.assertNotNull("Find all method for 'Job' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Job' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFindJobEntries() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobService.countAllJobs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Job> result = jobService.findJobEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Job' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Job' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobIntegrationTest.testSaveJob() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        Job obj = dod.getNewTransientJob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Job' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Job' identifier to be null", obj.getId());
        jobService.saveJob(obj);
        Assert.assertNotNull("Expected 'Job' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testDeleteJob() {
        Job obj = dod.getRandomJob();
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Job' failed to provide an identifier", id);
        obj = jobService.findJob(id);
        jobService.deleteJob(obj);
        Assert.assertNull("Failed to remove 'Job' with identifier '" + id + "'", jobService.findJob(id));
    }
    
}
