// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jobmatcher.domain;

import com.jobmatcher.domain.ResumeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ResumeIntegrationTest_Roo_Configurable {
    
    declare @type: ResumeIntegrationTest: @Configurable;
    
}
