// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jobmatcher.domain;

import com.jobmatcher.domain.Job;
import com.jobmatcher.domain.JobDataOnDemand;
import com.jobmatcher.domain.JobSeeker;
import com.jobmatcher.domain.JobSeekerDataOnDemand;
import com.jobmatcher.domain.SavedJob;
import com.jobmatcher.domain.SavedJobDataOnDemand;
import com.jobmatcher.service.SavedJobService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SavedJobDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SavedJobDataOnDemand: @Component;
    
    private Random SavedJobDataOnDemand.rnd = new SecureRandom();
    
    private List<SavedJob> SavedJobDataOnDemand.data;
    
    @Autowired
    JobDataOnDemand SavedJobDataOnDemand.jobDataOnDemand;
    
    @Autowired
    JobSeekerDataOnDemand SavedJobDataOnDemand.jobSeekerDataOnDemand;
    
    @Autowired
    SavedJobService SavedJobDataOnDemand.savedJobService;
    
    public SavedJob SavedJobDataOnDemand.getNewTransientSavedJob(int index) {
        SavedJob obj = new SavedJob();
        setJob(obj, index);
        setJobSeeker(obj, index);
        return obj;
    }
    
    public void SavedJobDataOnDemand.setJob(SavedJob obj, int index) {
        Job job = jobDataOnDemand.getRandomJob();
        obj.setJob(job);
    }
    
    public void SavedJobDataOnDemand.setJobSeeker(SavedJob obj, int index) {
        JobSeeker jobSeeker = jobSeekerDataOnDemand.getRandomJobSeeker();
        obj.setJobSeeker(jobSeeker);
    }
    
    public SavedJob SavedJobDataOnDemand.getSpecificSavedJob(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SavedJob obj = data.get(index);
        BigInteger id = obj.getId();
        return savedJobService.findSavedJob(id);
    }
    
    public SavedJob SavedJobDataOnDemand.getRandomSavedJob() {
        init();
        SavedJob obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return savedJobService.findSavedJob(id);
    }
    
    public boolean SavedJobDataOnDemand.modifySavedJob(SavedJob obj) {
        return false;
    }
    
    public void SavedJobDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = savedJobService.findSavedJobEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SavedJob' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SavedJob>();
        for (int i = 0; i < 10; i++) {
            SavedJob obj = getNewTransientSavedJob(i);
            try {
                savedJobService.saveSavedJob(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
