// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jobmatcher.domain;

import com.jobmatcher.domain.CoverLetter;
import com.jobmatcher.domain.CoverLetterDataOnDemand;
import com.jobmatcher.domain.Job;
import com.jobmatcher.domain.JobApplicant;
import com.jobmatcher.domain.JobApplicantDataOnDemand;
import com.jobmatcher.domain.JobDataOnDemand;
import com.jobmatcher.domain.JobSeeker;
import com.jobmatcher.domain.JobSeekerDataOnDemand;
import com.jobmatcher.domain.Resume;
import com.jobmatcher.domain.ResumeDataOnDemand;
import com.jobmatcher.service.JobApplicantService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JobApplicantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JobApplicantDataOnDemand: @Component;
    
    private Random JobApplicantDataOnDemand.rnd = new SecureRandom();
    
    private List<JobApplicant> JobApplicantDataOnDemand.data;
    
    @Autowired
    CoverLetterDataOnDemand JobApplicantDataOnDemand.coverLetterDataOnDemand;
    
    @Autowired
    JobDataOnDemand JobApplicantDataOnDemand.jobDataOnDemand;
    
    @Autowired
    JobSeekerDataOnDemand JobApplicantDataOnDemand.jobSeekerDataOnDemand;
    
    @Autowired
    ResumeDataOnDemand JobApplicantDataOnDemand.resumeDataOnDemand;
    
    @Autowired
    JobApplicantService JobApplicantDataOnDemand.jobApplicantService;
    
    public JobApplicant JobApplicantDataOnDemand.getNewTransientJobApplicant(int index) {
        JobApplicant obj = new JobApplicant();
        setCoverLetter(obj, index);
        setJob(obj, index);
        setJobSeeker(obj, index);
        setResume(obj, index);
        return obj;
    }
    
    public void JobApplicantDataOnDemand.setCoverLetter(JobApplicant obj, int index) {
        CoverLetter coverLetter = coverLetterDataOnDemand.getRandomCoverLetter();
        obj.setCoverLetter(coverLetter);
    }
    
    public void JobApplicantDataOnDemand.setJob(JobApplicant obj, int index) {
        Job job = jobDataOnDemand.getRandomJob();
        obj.setJob(job);
    }
    
    public void JobApplicantDataOnDemand.setJobSeeker(JobApplicant obj, int index) {
        JobSeeker jobSeeker = jobSeekerDataOnDemand.getRandomJobSeeker();
        obj.setJobSeeker(jobSeeker);
    }
    
    public void JobApplicantDataOnDemand.setResume(JobApplicant obj, int index) {
        Resume resume = resumeDataOnDemand.getRandomResume();
        obj.setResume(resume);
    }
    
    public JobApplicant JobApplicantDataOnDemand.getSpecificJobApplicant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JobApplicant obj = data.get(index);
        BigInteger id = obj.getId();
        return jobApplicantService.findJobApplicant(id);
    }
    
    public JobApplicant JobApplicantDataOnDemand.getRandomJobApplicant() {
        init();
        JobApplicant obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return jobApplicantService.findJobApplicant(id);
    }
    
    public boolean JobApplicantDataOnDemand.modifyJobApplicant(JobApplicant obj) {
        return false;
    }
    
    public void JobApplicantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = jobApplicantService.findJobApplicantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JobApplicant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JobApplicant>();
        for (int i = 0; i < 10; i++) {
            JobApplicant obj = getNewTransientJobApplicant(i);
            try {
                jobApplicantService.saveJobApplicant(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
